# Importing The Libraries

In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing The Dataset

In [17]:
dataset = pd.read_csv('Data.csv')
# X is the independent variable dataset (feature set)
# matrix of features X
# iloc means locate indexes, it will take the indexes of rows and columns you want to add
# iloc[range of rows, range of columns]
# range X:y means [X, y) => X is included, y is excluded
X = dataset.iloc[:, :-1].values
# dependent variable vector, -1 is the last column
y = dataset.iloc[:, -1].values

In [18]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [19]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking Care of Missing Data

In [20]:
from sklearn.impute import SimpleImputer
# making an object of the SimpleImputer class
# passing the missing_values and strategy as arguments to SimpleImputer object
# np.nan means that we want to replace missing values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# applying the imputer on the matrix of features (independent variables)
# fit() method expects all the numerical columns of the features x
# this connects our imputer with the matrix of features
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [21]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# ENCODING CATEGORICAL DATA

**Encoding the Independent Variable**

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# create an obj of ColumnTransformer, which take 2 arguments
# argument1 defines what kind of transformation should take place
# argument2 defines that we want to keep the columns, which weren't used
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# now connecting the transformer object with the data matrix
# can do it in 1 step using the fit_transform() method
# using the np.array() method to convert output to numpy array
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


**Encoding the Dependent Variable**

In [24]:
from sklearn.preprocessing import LabelEncoder

# create an obj of LabelEncoder, which takes no arguments
le = LabelEncoder()

# calling the fit_transform() method on le and passing dependent variable y
# we don't need to convert it to numpy array either
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into the Training set and Test set

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [27]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [28]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [29]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [30]:
print(y_test)

[0 1]


# Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
print(X_train)

[[-0.77459667 -0.57735027  1.29099445 -0.19159184 -1.07812594]
 [-0.77459667  1.73205081 -0.77459667 -0.01411729 -0.07013168]
 [ 1.29099445 -0.57735027 -0.77459667  0.56670851  0.63356243]
 [-0.77459667 -0.57735027  1.29099445 -0.30453019 -0.30786617]
 [-0.77459667 -0.57735027  1.29099445 -1.90180114 -1.42046362]
 [ 1.29099445 -0.57735027 -0.77459667  1.14753431  1.23265336]
 [-0.77459667  1.73205081 -0.77459667  1.43794721  1.57499104]
 [ 1.29099445 -0.57735027 -0.77459667 -0.74014954 -0.56461943]]


In [33]:
print(X_test)

[[-0.77459667  1.73205081 -0.77459667 -1.46618179 -0.9069571 ]
 [ 1.29099445 -0.57735027 -0.77459667 -0.44973664  0.20564034]]
