Importing the necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

Load the dataset

In [40]:
dataset = pd.read_csv('titanic.csv')
xMatrix = dataset.iloc[:, :]

Identify the categorical data

In [ ]:
columnsWithCategoricalData = ['Sex', 'Embarked', 'Pclass']

Implement an instance of the ColumnTransformer class

In [41]:
columnTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), columnsWithCategoricalData)], remainder = 'passthrough')

Apply the fit_transform method on the instance of ColumnTransformer

In [43]:
xMatrixCategorized = columnTransformer.fit_transform(xMatrix)

Convert the output into a NumPy array

In [44]:
X = np.array(xMatrixCategorized)

Use LabelEncoder to encode binary categorical data

In [45]:
yVctr = dataset.iloc[:,1]
lEncoder = LabelEncoder()
y = lEncoder.fit_transform(yVctr)

Print the updated matrix of features and the dependent variable vector

In [46]:
print(X)
print(y)

[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [1.